/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.torryharris.sample;

import com.torryharris.sample.verticles.Apiverticle;
import io.vertx.core.Vertx;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static final Logger LOGGER = LogManager.getLogger(App.class);
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(Apiverticle.class.getName())
                .onFailure(ERROR ->
                        LOGGER.error("Error while starting API verticle", ERROR));
    }

}
